#BANCO DE DADOS EM PYTHON
#EXTENSÃO SQL DB VIEWER - PARA VISUALIZAR O BANCO DE DADOS

import sqlite3 #IMPORTANDO UM BANCO DE DADOS DA BIBLIOTECA DO PYTHON
banco = sqlite3.connect('treinando_banco.db') #NESSA LINHA CRIA O BANCO DE DADOS - NOMEANDO O NOME DO BANCO DE DADOS E INSERINDO EM UMA VARIÁVEL
cursor = banco.cursor() #CURSOR E PARA PESQUISAR
cursor.execute("CREATE TABLE pessoas(nome text, idade integer, email text)")
cursor.execute("INSERT INTO pessoas VALUES('Gustavo', 63, 'lrgtvmito@gmail.com')") #COLOCANDO AS INFORMAÇÕES NO BANCO DE DADOS - TABELA
banco.commit() #INSERINDO (CONFIRMANDO) AS INFORMAÇÕES PARA SEREM UPADAS NO BANCO DE DADOS

#PARA ACESSAR OS DADOS NO BANCO DE DADOS DB

cursor.execute("SELECT * FROM pessoas") #SELECT PARA ACESSAR TABELA
print(cursor.fetchall()) #FETCHALL É UM COMANDO DO BANCO DE DADOS PARA LER
